name: Build
run-name: ${{ github.actor }} initiated build

on:
  push:
    branches: ["dev", "staging"]

  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install NodeJs and NPM
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Build Frontend
        run: |-
          cd frontend
          npm i
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./frontend/dist
